export const dynamic = "force-dynamic";
import Link from "next/link";
import AppShell from "@/components/layout/AppShell";
import BusinessNav from "@/components/istream/BusinessNav";
import { getFinancialControl } from "@/lib/actions/financial-control.actions";

export default async function ExpensesPage({ searchParams }: { searchParams: Promise<{ year?: string; status?: string }> }) {
  const params=await searchParams; const year=Number(params.year)||new Date().getFullYear(); const {expenses}=await getFinancialControl(year); const rows=params.status?expenses.filter((e:any)=>e.paymentStatus===params.status):expenses; const money=(v:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(v); const total=rows.reduce((s:number,e:any)=>s+e.actualCost,0); const unpaid=rows.filter((e:any)=>e.paymentStatus!=="PAID").reduce((s:number,e:any)=>s+e.actualCost,0);
  return <AppShell title="Istream Business"><BusinessNav/><div className="head"><div><h1>All Job Expenses</h1><p>One ledger across every Istream job.</p></div><div><Link href={`/istream/expenses?year=${year-1}`}>←</Link><strong>{year}</strong><Link href={`/istream/expenses?year=${year+1}`}>→</Link></div></div><div className="cards"><div><span>Total actual expenses</span><strong>{money(total)}</strong></div><div><span>Supplier payments due</span><strong>{money(unpaid)}</strong></div><div><span>Entries</span><strong>{rows.length}</strong></div></div><div className="filters"><Link href={`/istream/expenses?year=${year}`}>All</Link><Link href={`/istream/expenses?year=${year}&status=UNPAID`}>Unpaid</Link><Link href={`/istream/expenses?year=${year}&status=PART_PAID`}>Part paid</Link><Link href={`/istream/expenses?year=${year}&status=PAID`}>Paid</Link></div><div className="table"><table><thead><tr>{["Date","Job","Client","Supplier","Category","Description","Estimate","Actual","Payment","Reference"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((e:any)=><tr key={e.id}><td>{new Date(e.paymentDate||e.createdAt).toLocaleDateString("en-GB")}</td><td><Link href={`/projects/${e.projectId}`}>{e.project.jobNo}</Link></td><td>{e.project.quotations[0]?.client.company||"–"}</td><td>{e.supplier}</td><td>{e.category}</td><td>{e.description}</td><td>{money(e.estimatedCost)}</td><td>{money(e.actualCost)}</td><td>{e.paymentStatus.replace("_"," ")}</td><td>{e.reference||"–"}</td></tr>)}{!rows.length&&<tr><td colSpan={10}>No expenses for this selection.</td></tr>}</tbody></table></div><style>{`.head{display:flex;justify-content:space-between;align-items:end}.head h1{margin:0}.head p{color:#94a3b8}.head div:last-child{display:flex;gap:12px}.head a,.table a{color:#60a5fa}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:20px 0}.cards div{background:#0f172a;border:1px solid #334155;border-radius:10px;padding:15px}.cards span{display:block;color:#94a3b8}.cards strong{font-size:21px}.filters{display:flex;gap:8px;margin-bottom:14px}.filters a{background:#334155;color:white;padding:8px 11px;border-radius:7px;text-decoration:none}.table{overflow-x:auto;background:#1e293b;border:1px solid #334155;border-radius:12px}table{width:100%;min-width:1100px;border-collapse:collapse}th,td{text-align:left;padding:10px;border-bottom:1px solid #334155;font-size:13px}th{color:#cbd5e1}@media(max-width:650px){.cards{grid-template-columns:1fr}}`}</style></AppShell>;
}
