ALTER TABLE "Project" ADD COLUMN "closedAt" TIMESTAMP(3);
ALTER TABLE "Project" ADD COLUMN "closureNote" TEXT;
ALTER TABLE "Finance" ADD COLUMN "invoiceNo" TEXT;
ALTER TABLE "Finance" ADD COLUMN "invoiceDate" TIMESTAMP(3);
ALTER TABLE "Finance" ADD COLUMN "invoiceAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Finance" ADD COLUMN "amountReceived" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Finance" ADD COLUMN "paymentDate" TIMESTAMP(3);
ALTER TABLE "Finance" ADD COLUMN "paymentRef" TEXT;
