"use client";
import { useState } from "react";
import { saveMonthlyBudgets } from "@/lib/actions/financial-control.actions";

export default function BudgetManager({ year, initial }: { year: number; initial: any[] }) {
  const [rows, setRows] = useState(initial); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false);
  const monthName = (month: number) => new Date(year, month, 1).toLocaleString("en-GB", { month: "long" });
  const change = (month: number, patch: any) => setRows(rows.map((row) => row.month === month ? { ...row, ...patch } : row));
  async function save() { setSaving(true); setSaved(false); await saveMonthlyBudgets(year, rows); setSaving(false); setSaved(true); }
  return <><div className="table"><table><thead><tr><th>Month</th><th>Sales budget</th><th>Expense budget</th><th>Budget profit</th><th>Notes</th></tr></thead><tbody>{rows.map((row) => <tr key={row.month}><td><strong>{monthName(row.month)}</strong></td><td><input type="number" value={row.salesBudget} onChange={(e) => change(row.month, { salesBudget: Number(e.target.value) })}/></td><td><input type="number" value={row.expenseBudget} onChange={(e) => change(row.month, { expenseBudget: Number(e.target.value) })}/></td><td>{new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(row.salesBudget - row.expenseBudget)}</td><td><input value={row.notes} onChange={(e) => change(row.month, { notes: e.target.value })}/></td></tr>)}</tbody></table></div><div className="actions"><button disabled={saving} onClick={save}>{saving ? "Saving…" : `Save ${year} budget`}</button>{saved && <span>Budget saved.</span>}</div><style jsx>{`.table{overflow-x:auto;background:#1e293b;border:1px solid #334155;border-radius:12px}table{width:100%;min-width:850px;border-collapse:collapse}th,td{text-align:left;padding:11px;border-bottom:1px solid #334155}th{color:#cbd5e1}input{width:100%;box-sizing:border-box;padding:9px;border:1px solid #475569;border-radius:7px;background:#0f172a;color:white}.actions{display:flex;align-items:center;gap:12px;margin-top:18px}button{border:0;border-radius:8px;background:#2563eb;color:white;font-weight:700;padding:12px 18px;cursor:pointer}.actions span{color:#86efac}`}</style></>;
}
