"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { saveCatalogueItem, setCatalogueItemActive } from "@/lib/actions/quotation.actions";
type Item = { id: string; code: string; description: string; unitPrice: number; active: boolean };
const empty = { code: "", description: "", unitPrice: 0, active: true };
export default function CatalogueManager({ items }: { items: Item[] }) {
  const router = useRouter(); const [form, setForm] = useState<any>(empty); const [message, setMessage] = useState(""); const style = { width: "100%", boxSizing: "border-box" as const, border: "1px solid #475569", borderRadius: 7, background: "#0F172A", color: "white", padding: 10 };
  async function save() { const result = await saveCatalogueItem(form); setMessage(result.ok ? "Catalogue item saved." : result.error); if (result.ok) { setForm(empty); router.refresh(); } }
  async function toggle(item: Item) { await setCatalogueItemActive(item.id, !item.active); router.refresh(); }
  return <div className="layout"><section className="card"><h2>{form.id ? "Edit item" : "New catalogue item"}</h2><label>Item code<input style={style} value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></label><label>Quotation description<textarea rows={5} style={style} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Standard unit price (USD)<input type="number" min="0" step="0.01" style={style} value={form.unitPrice} onChange={e=>setForm({...form,unitPrice:Number(e.target.value)})}/></label><div><button onClick={save}>Save item</button>{form.id&&<button className="secondary" onClick={()=>setForm(empty)}>Cancel</button>}</div>{message&&<p>{message}</p>}</section><section className="card list"><h2>Catalogue & Pricing</h2>{items.map(item=><article key={item.id} className={item.active?"":"inactive"}><div><strong>{item.code}</strong><span>{item.description}</span><small>USD {item.unitPrice.toFixed(2)} · {item.active?"Active":"Inactive"}</small></div><div><button className="secondary" onClick={()=>setForm({...item})}>Edit</button><button className="secondary" onClick={()=>toggle(item)}>{item.active?"Deactivate":"Activate"}</button></div></article>)}</section><style jsx>{`.layout{display:grid;grid-template-columns:minmax(300px,420px) 1fr;gap:20px}.card{background:#1e293b;border:1px solid #334155;border-radius:12px;padding:20px}.card h2{margin-top:0}label{display:block;color:#cbd5e1;margin-bottom:14px;font-size:13px}label input,label textarea{margin-top:6px}button{border:0;border-radius:7px;background:#2563eb;color:white;padding:9px 13px;font-weight:700;cursor:pointer;margin-right:7px}.secondary{background:#334155}.list article{display:flex;justify-content:space-between;gap:14px;padding:13px 0;border-bottom:1px solid #334155}.list span,.list small{display:block;color:#cbd5e1;margin-top:4px}.list small{color:#94a3b8}.inactive{opacity:.55}@media(max-width:850px){.layout{grid-template-columns:1fr}}`}</style></div>;
}
