"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { archiveBusinessClient, saveBusinessClient } from "@/lib/actions/quotation.actions";
type Client = { id: string; company: string; contactName: string | null; address: string | null; vatTin: string | null; email: string | null; phone: string | null };
const empty = { company: "", contactName: "", address: "", vatTin: "", email: "", phone: "" };
export default function ClientsManager({ clients }: { clients: Client[] }) {
  const router = useRouter(); const [form, setForm] = useState<any>(empty); const [message, setMessage] = useState(""); const style = { width: "100%", boxSizing: "border-box" as const, border: "1px solid #475569", borderRadius: 7, background: "#0F172A", color: "white", padding: 10 };
  async function save() { const result = await saveBusinessClient(form); setMessage(result.ok ? "Client saved." : result.error); if (result.ok) { setForm(empty); router.refresh(); } }
  async function archive(id: string) { if (window.confirm("Archive this client? Existing quotations will remain available.")) { await archiveBusinessClient(id); router.refresh(); } }
  return <div className="layout"><section className="card"><h2>{form.id ? "Edit client" : "New client"}</h2>{[['Company','company'],['Contact person','contactName'],['VAT / TIN','vatTin'],['Email','email'],['Phone','phone']].map(([label,key]) => <label key={key}>{label}<input style={style} value={form[key] ?? ""} onChange={e => setForm({...form,[key]:e.target.value})}/></label>)}<label>Address<textarea rows={4} style={style} value={form.address ?? ""} onChange={e => setForm({...form,address:e.target.value})}/></label><div><button onClick={save}>Save client</button>{form.id && <button className="secondary" onClick={() => setForm(empty)}>Cancel</button>}</div>{message && <p>{message}</p>}</section><section className="card list"><h2>Clients</h2>{clients.map(client => <article key={client.id}><div><strong>{client.company}</strong><small>{client.contactName || "No contact"} · {client.vatTin || "No VAT/TIN"}</small></div><div><button className="secondary" onClick={() => setForm({...client})}>Edit</button><button className="secondary" onClick={() => archive(client.id)}>Archive</button></div></article>)}</section><style jsx>{`.layout{display:grid;grid-template-columns:minmax(300px,420px) 1fr;gap:20px}.card{background:#1e293b;border:1px solid #334155;border-radius:12px;padding:20px}.card h2{margin-top:0}label{display:block;color:#cbd5e1;margin-bottom:14px;font-size:13px}label input,label textarea{margin-top:6px}button{border:0;border-radius:7px;background:#2563eb;color:white;padding:9px 13px;font-weight:700;cursor:pointer;margin-right:7px}.secondary{background:#334155}.list article{display:flex;justify-content:space-between;gap:14px;padding:13px 0;border-bottom:1px solid #334155}.list small{display:block;color:#94a3b8;margin-top:4px}@media(max-width:850px){.layout{grid-template-columns:1fr}}`}</style></div>;
}
