export const dynamic = "force-dynamic";
import Link from "next/link";
import AppShell from "@/components/layout/AppShell";
import BusinessNav from "@/components/istream/BusinessNav";
import { getFinancialControl } from "@/lib/actions/financial-control.actions";
const pv=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;
const money=(v:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(v);
export default async function BusinessDashboard({searchParams}:{searchParams:Promise<{period?:string;view?:string;year?:string}>}){
  const p=await searchParams; const chosen=p.period&&/^\d{4}-\d{2}$/.test(p.period)?new Date(`${p.period}-01T12:00:00`):new Date(); const year=Number(p.year)||chosen.getFullYear(); const {months,jobs}=await getFinancialControl(year); const isYear=p.view==="year";
  const views=<div className="views"><Link className={!isYear?"active":""} href={`/istream/dashboard?period=${pv(chosen)}`}>Month View</Link><Link className={isYear?"active":""} href={`/istream/dashboard?view=year&year=${year}`}>Year View</Link></div>;
  if(isYear){const total=(k:string)=>months.reduce((s:number,r:any)=>s+r[k],0);const sales=total("invoiced"),direct=total("actualExpenses"),overheads=total("actualOverheads"),net=sales-direct-overheads;return <AppShell title="Istream Business"><BusinessNav/>{views}<div className="head"><div><h1>{year} Financial Overview</h1><p>Annual summary built from the twelve monthly periods.</p></div><div><Link href={`/istream/dashboard?view=year&year=${year-1}`}>← {year-1}</Link><Link href={`/istream/dashboard?view=year&year=${year+1}`}>{year+1} →</Link></div></div><div className="cards"><K label="Sales budget" value={money(total("salesBudget"))}/><K label="Actual sales" value={money(sales)}/><K label="Direct job costs" value={money(direct)}/><K label="Overheads" value={money(overheads)}/><K label="Gross profit" value={money(sales-direct)}/><K label="Net profit" value={money(net)}/><K label="Net margin" value={`${sales?(net/sales*100).toFixed(1):"0.0"}%`}/><K label="Capital expenditure" value={money(total("capitalExpenditure"))}/></div><div className="table"><table><thead><tr>{["Month","Sales budget","Actual sales","Direct costs","Overheads","Gross profit","Net profit","Cost variance"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{months.map((r:any)=><tr key={r.month}><td><Link href={`/istream/dashboard?period=${year}-${String(r.month+1).padStart(2,"0")}`}>{new Date(year,r.month,1).toLocaleString("en-GB",{month:"short"})}</Link></td><td>{money(r.salesBudget)}</td><td>{money(r.invoiced)}</td><td>{money(r.actualExpenses)}</td><td>{money(r.actualOverheads)}</td><td>{money(r.invoiced-r.actualExpenses)}</td><td>{money(r.invoiced-r.actualExpenses-r.actualOverheads)}</td><td>{money(r.expenseBudget+r.overheadBudget-r.actualExpenses-r.actualOverheads)}</td></tr>)}</tbody></table></div><Styles/></AppShell>}
  const month=chosen.getMonth(),row=months[month],prev=new Date(chosen.getFullYear(),month-1,1),next=new Date(chosen.getFullYear(),month+1,1);const pct=(a:number,b:number)=>b?`${(a/b*100).toFixed(1)}%`:a?"No budget":"0.0%";const gross=row.invoiced-row.actualExpenses,net=gross-row.actualOverheads;const due=jobs.reduce((s:number,j:any)=>s+Math.max(0,(j.finance?.invoiceAmount||j.finance?.approvedBudget||0)-(j.finance?.amountReceived||0)),0);const items=[['Sales budget',money(row.salesBudget),'Monthly target'],['Actual invoiced sales',money(row.invoiced),`${pct(row.invoiced,row.salesBudget)} of target`],['Quoted this month',money(row.quoted),'Sales pipeline created'],['Cash received',money(row.received),'Client receipts'],['Direct-cost budget',money(row.expenseBudget),'Job-cost allowance'],['Actual job costs',money(row.actualExpenses),`${pct(row.actualExpenses,row.expenseBudget)} of budget`],['Overhead budget',money(row.overheadBudget),'Monthly operating allowance'],['Actual overheads',money(row.actualOverheads),`${pct(row.actualOverheads,row.overheadBudget)} of budget`],['Gross profit',money(gross),'Sales less direct costs'],['Net operating profit',money(net),`Margin ${row.invoiced?(net/row.invoiced*100).toFixed(1):'0.0'}%`],['Total cost variance',money(row.expenseBudget+row.overheadBudget-row.actualExpenses-row.actualOverheads),'Positive is under budget'],['Client money due',money(due),'All open client balances']];
  return <AppShell title="Istream Business"><BusinessNav/>{views}<div className="head"><div><h1>Dashboard · {chosen.toLocaleString('en-GB',{month:'long',year:'numeric'})}</h1><p>Monthly budget, actuals and profitability.</p></div><div><Link href={`/istream/dashboard?period=${pv(prev)}`}>← Previous</Link><Link href={`/istream/dashboard?period=${pv(next)}`}>Next →</Link></div></div><div className="cards">{items.map(([label,value,detail])=><div key={label}><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>)}</div><Styles/></AppShell>
}
function K({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
function Styles(){return <style>{`.views{display:flex;gap:8px;margin-bottom:20px}.views a{padding:9px 13px;background:#334155;color:white;border-radius:8px;text-decoration:none}.views a.active{background:#2563eb}.head{display:flex;justify-content:space-between;align-items:end;gap:15px;margin-bottom:20px}.head h1{margin:0}.head p{color:#94a3b8}.head div:last-child{display:flex;gap:12px}.head a,.table a{color:#60a5fa}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:20px}.cards>div{background:#0f172a;border:1px solid #334155;border-radius:11px;padding:17px}.cards span{display:block;color:#94a3b8;font-size:12px}.cards strong{display:block;font-size:21px;margin-top:7px}.cards small{display:block;color:#7dd3fc;margin-top:6px}.table{overflow-x:auto;background:#1e293b;border:1px solid #334155;border-radius:12px}table{width:100%;min-width:1000px;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid #334155;text-align:right}th:first-child,td:first-child{text-align:left}th{color:#cbd5e1}@media(max-width:950px){.cards{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.cards{grid-template-columns:1fr}.head{display:grid}}`}</style>}
