export const dynamic = "force-dynamic";
import Link from "next/link";
import AppShell from "@/components/layout/AppShell";
import BusinessNav from "@/components/istream/BusinessNav";
import { getFinancialControl } from "@/lib/actions/financial-control.actions";

export default async function BusinessDashboard({ searchParams }: { searchParams: Promise<{ year?: string }> }) {
  const year = Number((await searchParams).year) || new Date().getFullYear(); const { months, jobs } = await getFinancialControl(year);
  const sum = (key: string) => months.reduce((total: number, row: any) => total + row[key], 0); const money = (v: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(v);
  const salesBudget = sum("salesBudget"), expenseBudget = sum("expenseBudget"), invoiced = sum("invoiced"), received = sum("received"), expenses = sum("actualExpenses"), quoted = sum("quoted");
  const due = jobs.reduce((total: number, job: any) => total + Math.max(0, (job.finance?.invoiceAmount || job.finance?.approvedBudget || 0) - (job.finance?.amountReceived || 0)), 0);
  return <AppShell title="Istream Business"><BusinessNav/><div className="head"><div><h1>Business Dashboard</h1><p>Budgets, sales, cash and job costs for {year}.</p></div><div><Link href={`/istream/dashboard?year=${year-1}`}>← {year-1}</Link><strong>{year}</strong><Link href={`/istream/dashboard?year=${year+1}`}>{year+1} →</Link></div></div>
    <div className="cards">{[["Sales budget",money(salesBudget)],["Quoted",money(quoted)],["Invoiced",money(invoiced)],["Cash received",money(received)],["Expense budget",money(expenseBudget)],["Actual expenses",money(expenses)],["Client money due",money(due)],["Actual cash profit",money(received-expenses)]].map(([label,value])=><div className="card" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
    <div className="table"><table><thead><tr>{["Month","Sales budget","Quoted","Invoiced","Received","Expense budget","Actual expenses","Profit","Sales variance","Cost variance"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{months.map((row:any)=><tr key={row.month}><td><strong>{new Date(year,row.month,1).toLocaleString("en-GB",{month:"short"})}</strong></td><td>{money(row.salesBudget)}</td><td>{money(row.quoted)}</td><td>{money(row.invoiced)}</td><td>{money(row.received)}</td><td>{money(row.expenseBudget)}</td><td>{money(row.actualExpenses)}</td><td>{money(row.invoiced-row.actualExpenses)}</td><td className={row.invoiced-row.salesBudget>=0?"good":"bad"}>{money(row.invoiced-row.salesBudget)}</td><td className={row.expenseBudget-row.actualExpenses>=0?"good":"bad"}>{money(row.expenseBudget-row.actualExpenses)}</td></tr>)}</tbody></table></div>
    <style>{`.head{display:flex;justify-content:space-between;align-items:end;gap:18px;margin-bottom:20px}.head h1{margin:0}.head p{color:#94a3b8}.head div:last-child{display:flex;gap:12px}.head a{color:#60a5fa}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:20px}.card{background:#0f172a;border:1px solid #334155;border-radius:11px;padding:16px}.card span{display:block;color:#94a3b8;font-size:12px}.card strong{display:block;margin-top:7px;font-size:20px}.table{overflow-x:auto;background:#1e293b;border:1px solid #334155;border-radius:12px}table{width:100%;min-width:1200px;border-collapse:collapse}th,td{text-align:right;padding:10px;border-bottom:1px solid #334155;font-size:13px}th:first-child,td:first-child{text-align:left}th{color:#cbd5e1}.good{color:#86efac}.bad{color:#fca5a5}@media(max-width:950px){.cards{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.cards{grid-template-columns:1fr}.head{display:grid}}`}</style>
  </AppShell>;
}
